
Part 2 (DDL Generation)

Submitted by: 
Rijesh Kumar, Tanya Garhwal, Charles Thiemele, Logan Butler
--------------------------------------------------------------------------------------
CREATE TABLE ENTITY (
	ID						NUMBER NOT NULL,
	NAME					VARCHAR2(20),
	TYPE					VARCHAR2(20) 
		CONSTRAINT CHECK (TYPE IN ('ENTITY', 'ATTRIBUTE')),		
	PRIMARY KEY (ID)
)

CREATE TABLE ATTRIBUTE (
	ID 						NUMBER NOT NULL,
	NAME 					VARCHAR2(20),
	PRIMARY KEY (ID)
)

CREATE TABLE RELATIONSHIP (
	ID						NUMBER NOT NULL,
	NAME					VARCHAR2(20),
	REL_TYPE				VARCHAR2(20)
		CONSTRAINT REL_TYPE_CONSTRAINT CHECK (REL_TYPE IN ('OneToOne', 'OneToMany', 'ManyToOne', 'ManyToMany')), 
	PRIMARY KEY (ID),
)

CREATE TABLE IS_A (
	LEFT_ENTITY_ID 			NUMBER NOT NULL,
	RIGHT_ENTITY_ID 		NUMBER NOT NULL,
	PRIMARY KEY (LEFT_ENTITY_ID, RIGHT_ENTITY_ID),
	FOREIGN KEY (LEFT_ENTITY_ID) REFERENCES ENTITY(ID),
	FOREIGN KEY (RIGHT_ENTITY_ID) REFERENCES ENTITY(ID)
)

CREATE TABLE HAS_ATTRIBUTE (
	ID 						NUMBER NOT NULL,
	ATTRIBUTE_ID 			NUMBER,
	ENTITY_ID 				NUMBER,
	PRIMARY KEY (ID),
	FOREIGN KEY (ATTRIBUTE_ID) REFERENCES ATTRIBUTE(ID),
	FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ID)
)


CREATE TABLE  HAS_RELATIONSHIP (
	ID 						NUMBER NOT NULL,
	RELATIONSHIP_ID 		NUMBER,
	ENTITY_ID 				NUMBER,
	PRIMARY KEY (ID),
	FOREIGN KEY (RELATIONSHIP_ID) REFERENCES RELATIONSHIP(ID),
	FOREIGN KEY (ENTITY_ID) REFERENCES ENTITY(ID)
	
)

