--ENTITIES

INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (1, 'Employee', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (2, 'TempHourly', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (3, 'Associate', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (4, 'Contractor', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (5, 'Promotion', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (6, 'Display', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (7, 'Store', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (8, 'Region', 'ENTITY' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (9, 'Product', 'ENTITY' );

INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (10, 'Name', 'ATTRIBUTE' ); 
INSERT INTO ENTITY (ID, NAME, TYPE) VALUES (11, 'Address', 'ATTRIBUTE' );  

--ATTRIBUTES


--RELATIONSHIP


--ISA
INSERT INTO IS_A (LEFT_ENTITY_ID, RIGHT_ENTITY_ID) VALUES (3, 1); -- Associate is a Employee 
INSERT INTO IS_A (LEFT_ENTITY_ID, RIGHT_ENTITY_ID) VALUES (2, 1); -- TempHourly is a Employee 

--HAS_ATTRIBUTE


--HAS_RELATIONSHIP