--1) --ALL_ENTS:
CREATE VIEW All_Ents AS 
SELECT E.NAME FROM ENTITY E where E.TYPE='ENTITY'; 

--2) --ALL_ATTS:
CREATE VIEW All_Atts AS 
SELECT NAME FROM ATTRIBUTE; 

--3) --All_Keys:
CREATE VIEW All_Keys AS 
SELECT E.ID FROM ENTITY E where E.TYPE='ENTITY'; 

--4) --All_Rels:
CREATE VIEW All_Rels AS 
SELECT NAME FROM RELATIONSHIP; 




--5) --EntAtt:
CREATE VIEW EntAtt AS
SELECT ENTITY_ID, ATTRIBUTE_ID FROM HAS_ATTRIBUTE

--6) --RelEnt:
CREATE VIEW RelEnt AS
SELECT rel.NAME, has_rel.ENTITY_ID 
FROM RELATIONSHIP rel JOIN HAS_RELATIONSHIP has_rel
	ON rel.ID = has_rel.RELATIONSHIP_ID

--7) --RelAtt:


--8) --AttDatatype:
CREATE VIEW AttDatatype AS
SELECT NAME, DATA_TYPE FROM ATTRIBUTE;

--9) --EntKey:


--10) --KeyAttr: